cc=main.cpp Dequeue.cpp Stack.cpp
header=Dequeue.h Stack.h
all=$(cc)
out=dequeue.exe # Replace with your output file.
flags=-Wall -Wextra -std=c++11
comp=g++ $(flags) $(cc) -o $(out)

batch=out.bat

c: $(cc)
	$(comp)

r:
	.\$(batch) .\$(out)
